name: Playwright Tests
on: push

jobs:
  e2e-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    # Update env variables with your own database credentials
    env:
      PGHOST: localhost
      PGDATABASE: next_js_example_winter_2023
      PGUSERNAME: next_js_example_winter_2023
      PGPASSWORD: next_js_example_winter_2023
    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER next_js_example_winter_2023 PASSWORD 'next_js_example_winter_2023'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=next_js_example_winter_2023 next_js_example_winter_2023
      - uses: actions/checkout@v3
      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1
      - run: yarn migrate up
      # Also generates next-env.d.ts, required for tsc
      - name: Build localhost
        run: yarn build
      - name: Run TypeScript Compiler
        run: yarn tsc
      - name: Run ESLint
        run: yarn eslint . --max-warnings 0
      - name: Run Stylelint
        run: yarn stylelint '**/*.{css,scss,less,js,tsx}'
      - name: Install Playwright
        run: yarn playwright install --with-deps chromium
      - name: Run tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-screenshots-videos
          path: playwright/test-results/
