name: Jest tests
on: push

jobs:
  build:
    name: Jest tests
    # Tell the action to use the latest
    # version of Ubuntu (a Linux flavor)
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
      # Use the official Checkout action (clones the GitHub repo):
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      # Run the Jest unit tests
      - run: yarn jest
